config/routes.rb
Rails.application.routes.draw do
  delete '/admin/comments/clear_junk' => 'admin/comments#clear_junk', :as => :clear_junk

  namespace :admin do
    resource :profile, :controller => 'users'
    resource :user_session, :only => :create
    resources :posts do
      post :publish
      post :quietly_publish
      post :revert
      post :takedown
    end
    resources :comments do
      post :junk
      post :notjunk
      collection do
        post :bulk_action
      end
    end
    resources :assets
    resources :tags
    resources :dashboard, :only => :index
  end

  get '/register' => 'admin/users#new'
  get '/login' => 'admin/user_sessions#new'
  get '/logout' => 'admin/user_sessions#destroy'

  get '/admin' => redirect('/admin/dashboard')

  get '/posts.:format' => 'home#posts', :format => 'atom'
  get '/comments.:format', :controller => 'home', :action => 'comments', :format => 'atom'

  get '/:tag/posts.:format', :controller => 'home', :action => 'posts', :format => 'atom'
  get '/:post/comments.:format', :controller => 'home', :action => 'comments', :format => 'atom'

  get '/tag/:label' => 'home#tag'
  get '/tag/:label.:format' => 'home#tag'

  get '/:permalink' => 'home#post'
  get '/:permalink/preview' => 'home#preview'
  get '/:permalink.:format' => 'home#post'

  post '/:permalink' => 'home#post'

  get ':controller(/:id(/:action(/:id)))'
  get ':controller(/:id(/:action(/:id(.:format))))'

  root :to => "home#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Rakismet::Model

  belongs_to :post

  validate :check_mandatory_fields
  validates_presence_of :author, :author_email, :content, :on => :update

  scope :by_date_descending, -> { order(created_at: :desc) }
  scope :by_date_ascending, -> { order(created_at: :asc) }
  scope :for_post, ->(post) { where('post_id = ?', post.id) }
  scope :for_published_posts, -> { joins('JOIN posts p ON p.id = comments.post_id').where('version IS NOT NULL') }
  scope :for_author, ->(user) { joins('JOIN posts p ON comments.post_id = p.id').where('p.user_id = ?', user.id) }
  scope :not_junk, -> { where('junk = ?', false) }
  scope :junk, -> { where('junk = ?', true) }
  scope :with_tag, ->(tag) { joins('JOIN posts p ON p.id = comments.post_id', 'JOIN posts_tags pt ON pt.post_id = p.id').where('pt.tag_id = ?', tag.id) }
  scope :since, ->(date) { where('created_at > ?', date) }

  before_create :check_for_spam

  attr_accessor :recaptcha_failed

  def content_html
    markdown(self.content)
  end

  def content_text
    Nokogiri::HTML(content_html).xpath("//text()").text
  end

  def permalink
    "#{self.post.permalink}##{self.id}"
  end

  def permalink_url
    self.post.permalink_url ? "#{self.post.permalink_url}##{self.id}" : nil
  end

  def full_permalink_url
    permalink_url ? "http://#{File.join(APP_CONFIG.domain, permalink_url)}" : nil
  end

  def avatar_url(default_host=nil, default_port=nil)
    Avatar.avatar_url(self.author_email, default_host, default_port)
  end

  def junk!
    unless self.junk?
      self.spam! if using_askimet?
      self.junk = true
      self.save
    end
  end

  def not_junk!
    if self.junk?
      self.ham! if using_askimet?
      self.junk = false
      self.save
    end
  end

  private
    def check_mandatory_fields
      return unless self.new_record?
      missing = []
      missing << 'your name' if self.author.blank?
      missing << 'your email address' if self.author_email.blank?
      missing << 'your comment' if self.content.blank?
      missing_message = if missing.size > 0
        "Please fill in " + (missing.size == 1 ? message = missing.first : missing[0..-2].join(', ') + ' and ' + missing[-1])
      else
        nil
      end

      if recaptcha_failed
        message = (missing_message.blank? ? "Please" : "#{missing_message} and") + " confirm you're not a robot"
      else
        message = missing_message
      end

      errors[:base] << message unless message.blank?
    end

    def check_for_spam
      self.junk = true if using_askimet? and self.spam?
    end

    def using_askimet?
      APP_CONFIG.akismet_enabled and !APP_CONFIG.akismet_api_key.blank?
    end

    def markdown(s)
      BlueCloth.new(keep_linebreaks(s)).to_html.html_safe
    end

    def keep_linebreaks(s)
      s.gsub("\r\n", "\n").gsub("\r", "\n").gsub("\n\n", "\r\r").gsub("\n", "  \n").gsub("\r\r", "\n\n")
    end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  layout 'admin'

  before_filter :require_user

  DEFAULT_PAGE_SIZE = 20

  def index
    @posts = Post.by_date_descending
    @post = Post.find(params[:post_id]) unless params[:post_id].blank?
    @junk_status = params[:junk_status] || 'all'
    @page = (params[:page] || 1).to_i
    @per_page = (params[:per_page] || DEFAULT_PAGE_SIZE).to_i
    all_comments = Comment.by_date_descending
    all_comments = all_comments.for_post(@post) if @post
    @comments = all_comments if @junk_status == 'all'
    @comments = all_comments.send(@junk_status.to_sym) unless @junk_status == 'all'
    @comments = @comments.paginate(:page => @page, :per_page => @per_page)
    @counts = {:all => all_comments.count, :junk => all_comments.junk.count, :not_junk => all_comments.not_junk.count}
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def edit
    @comment = Comment.find(params[:id])
    if check_access(@comment, 'edit')
      @user = @current_user
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if params[:cancel]
      redirect_to(admin_comment_path(@comment))
    elsif check_access(@comment, 'update')
      @comment.attributes = comment_param
      did_change = @comment.changed?
      if @comment.save
        flash[:notice] = 'No changes' unless did_change
        flash[:notice] = 'Updated comment' if did_change
        redirect_to(admin_comment_path(@comment))
      else
        render :action => "edit"
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if check_access(@comment, 'delete')
      @comment.destroy
      flash[:notice] = 'Deleted comment'
      redirect_to(admin_comments_path(:post_id => @comment.post.id))
    end
  end

  def junk
    @comment = Comment.find(params[:comment_id])
    if check_access(@comment, 'junk')
      @comment.junk!
      redirect_to(admin_comment_path(@comment, :post_id => @comment.post.id))
    end
  end

  def notjunk
    @comment = Comment.find(params[:comment_id])
    if check_access(@comment, 'unjunk')
      @comment.not_junk!
      redirect_to(admin_comment_path(@comment, :post_id => @comment.post.id))
    end
  end

  def bulk_action
    count = 0
    if params[:check].present?
      if params[:delete].present?
        action = :destroy
        description = 'deleted'
      elsif params[:junk].present?
        action = :junk!
        description = 'updated'
      elsif params[:notjunk].present?
        action = :not_junk!
        description = 'updated'
      end
      params[:check].keys.each do |comment_id|
        comment = Comment.find(comment_id)
        if comment.post.user == @current_user
          comment.send(action)
          count += 1
        end
      end
    end
    flash[:notice] = "#{count} comments #{description}" unless count == 0
    flash[:error] = 'No valid comments selected' if count == 0
    redirect_to(admin_comments_path)
  end

  def clear_junk
    comments_ids = Comment.where(:junk => true).map(&:id)
    Comment.delete(comments_ids)
    flash[:notice] = "#{comments_ids.count} junk comment#{comments_ids.count == 1 ? '' : 's'} deleted"
    redirect_to admin_dashboard_index_path
  end

  private
    def check_access(comment, action)
      return true if comment.post.user == @current_user
      flash[:error] = "Can only #{action} comments for your own posts"
      redirect_to(admin_comment_path(comment))
      false
    end

    def comment_param(_params = params)
      _params.require(:comment).permit(:author, :author_email, :author_url, :content, :created_at)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comment_count_description(post)
    not_junk_count = post.comments.not_junk.count
    return '1 comment' if not_junk_count == 1
    "#{not_junk_count} comments"
  end
  
  def comment_count_link(post)
    not_junk_count = post.comments.not_junk.count
    junk_count = post.comments.junk.count
    description = [not_junk_count.to_s, junk_count.to_s].join(' + ')
    post.comments.count == 0 ? '0' : link_to("#{description}", admin_comments_path(:post_id => post.id))
  end
  
  def comments_disabled?
    (defined? APP_CONFIG and APP_CONFIG.comments_disabled) || false
  end
end

app/views/admin/comments/_form.html.haml
:javascript
  $(document).ready(function() {
     $("#markItUp").markItUp(mySettings);
  });
%div
  = form.label :created_at
  = form.text_field :created_at
%div
  = form.label :author
  = form.text_field :author
%div
  = form.label :author_email
  = form.text_field :author_email
%div
  = form.label :author_url
  = form.text_field :author_url
%div
  = form.label :content, 'Content'
  = form.text_area :content, :id => 'markItUp'

app/views/admin/comments/edit.html.haml
%h2
  Edit comment #{@comment.id}
%fieldset.admin
  = form_for @comment, :url => admin_comment_path(@comment) do |form|
    = render :partial => '/admin/errors', :locals => { :errors => @comment.errors }
    = render :partial => 'form', :object => form
    .actions
      = form.submit 'Update', :class => 'button', :name => 'update'
      = form.submit 'Cancel', :class => 'button', :name => 'cancel'

app/views/admin/comments/index.html.haml
%h2 Comments
%fieldset.admin
  = will_paginate @comments
  = form_tag(admin_comments_path, :method => 'get', :class => 'filters') do
    Post
    \#{select_tag(:post_id, options_for_select([["All (#{Comment.not_junk.count} + #{Comment.junk.count})", nil]] + @posts.select{ |p| p.comments.count > 0 }.collect{|p| ["#{p.title || p.title_draft} (#{p.comments.not_junk.count} + #{p.comments.junk.count})", p.id]}, @post.nil? ? nil : @post.id))}
    Status
    \#{select_tag(:junk_status, options_for_select([["All (#{@counts[:all]})", 'all'],["Not junk (#{@counts[:not_junk]})", 'not_junk'], ["Junk (#{@counts[:junk]})", 'junk']], @junk_status))}
    \#{submit_tag 'filter'}
  - if @comments.empty?
    No comments yet
  - else
    = form_tag(bulk_action_admin_comments_path, :method => 'post') do
      %table.comments
        %tr
          %th= check_box_tag 'all', 1, false, :class => 'check-all'
          %th Date
          %th Author
          %th  
          %th Comment
        - @comments.each do |comment|
          %tr{:class => "#{cycle('dark', 'light')}#{" not-author" if comment.post.nil? or comment.post.user != @current_user}"}
            %th= check_box_tag "check[#{comment.id}]", 1, false, :class => 'checkable'
            %td.timestamp
              = format_timestamp(comment.created_at, '<br/>')
            %td
              %a{:name => comment.id}
              = image_tag comment.avatar_url(request.host, request.port)
              = comment.author if comment.author_url.blank?
              = link_to(comment.author, comment.author_url) unless comment.author_url.blank?
              %br/
              = link_to(comment.author_email, 'mailto:' + comment.author_email)
            %td.junk-stamp
              = image_tag('/images/junk.png') if comment.junk?
            %td.comment
              - unless comment.junk? or comment.permalink_url.blank?
                %span.permalink
                  = link_to(image_tag('/images/permalink.png', :title => 'permalink'), comment.permalink_url)
              = link_to((comment.post.title || comment.post.title_draft) + "##{comment.id}", admin_comment_path(comment))
              %br/
              = truncate_string(comment.content, 175)
      = will_paginate @comments
      .bulk-actions
        = submit_tag 'delete selected', :name => 'delete', :class => 'must-confirm', :message => 'Are you sure you want to delete all the selected comments?'
        = submit_tag 'junk selected', :name => 'junk', :class => 'must-confirm', :message => 'Are you sure all the selected comments are junk?'
        = submit_tag 'not junk selected', :name => 'notjunk', :class => 'must-confirm', :message => 'Are you sure all the selected comments are not junk?'

app/views/admin/comments/show.html.haml
%h2
  Comment #{@comment.id}
%fieldset.admin
  .show
    .junk-stamp
      = image_tag('/images/junk.png') if @comment.junk?
    %span
      %label Date:
      = format_timestamp(@comment.created_at)
    %span
      %label Author:
      = @comment.author
    %span
      %label Author Email:
      = link_to(@comment.author_email, 'mailto:' + @comment.author_email)
    %span
      %label Author Url:
      = link_to(@comment.author_url, @comment.author_url) unless @comment.author_url.blank?
    %span
      %label User IP:
      = @comment.user_ip
    %span
      %label User Agent:
      = @comment.user_agent
    %span
      %label Referrer:
      = link_to(@comment.referrer, @comment.referrer) unless @comment.referrer.blank?
    %span
      %label Post:
      = link_to(@comment.post.title_draft, admin_post_path(@comment.post))
    %span
      %label Permalink:
      = link_to @comment.permalink, @comment.permalink_url if @comment.permalink_url
      = @comment.permalink unless @comment.permalink_url
    .actions
      = button(admin_comments_path(:post_id => @comment.post.id), '« Comments'.html_safe)
      = button(edit_admin_comment_path(@comment), 'Edit')
      = button_with_confirmation(admin_comment_notjunk_path(@comment), 'Not junk', 'Are you sure this comment is not junk?', 'post') if @comment.junk?
      = button_with_confirmation(admin_comment_junk_path(@comment), 'Junk', 'Are you sure this comment is junk?', 'post') unless @comment.junk?
      = button_with_confirmation(admin_comment_path(@comment), 'Delete', 'Are you sure you want to delete this comment?', 'delete')
%fieldset.content
  .comment
    = @comment.content_html