config/routes.rb
Rails.application.routes.draw do
  delete '/admin/comments/clear_junk' => 'admin/comments#clear_junk', :as => :clear_junk

  namespace :admin do
    resource :profile, :controller => 'users'
    resource :user_session, :only => :create
    resources :posts do
      post :publish
      post :quietly_publish
      post :revert
      post :takedown
    end
    resources :comments do
      post :junk
      post :notjunk
      collection do
        post :bulk_action
      end
    end
    resources :assets
    resources :tags
    resources :dashboard, :only => :index
  end

  get '/register' => 'admin/users#new'
  get '/login' => 'admin/user_sessions#new'
  get '/logout' => 'admin/user_sessions#destroy'

  get '/admin' => redirect('/admin/dashboard')

  get '/posts.:format' => 'home#posts', :format => 'atom'
  get '/comments.:format', :controller => 'home', :action => 'comments', :format => 'atom'

  get '/:tag/posts.:format', :controller => 'home', :action => 'posts', :format => 'atom'
  get '/:post/comments.:format', :controller => 'home', :action => 'comments', :format => 'atom'

  get '/tag/:label' => 'home#tag'
  get '/tag/:label.:format' => 'home#tag'

  get '/:permalink' => 'home#post'
  get '/:permalink/preview' => 'home#preview'
  get '/:permalink.:format' => 'home#post'

  post '/:permalink' => 'home#post'

  get ':controller(/:id(/:action(/:id)))'
  get ':controller(/:id(/:action(/:id(.:format))))'

  root :to => "home#index"
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :title
  validate :file_does_not_exist

  has_attached_file :upload, :styles => { :thumb => "100x100>" }, :path => "/assets/:style/:basename.:extension",
                    :storage => :s3, :s3_credentials => "#{::Rails.root}/config/s3.yml"

  validates_attachment_presence :upload
  validates_attachment_content_type :upload, :content_type => /\Aimage/

  before_post_process :is_image?

  scope :by_date_descending, -> { order(upload_updated_at: :desc) }

  DEFAULT_THUMBNAIL_URL = '/images/file.png'

  def is_image?
    !(upload_content_type =~ /^image.*/).nil?
  end

  def url
    self.upload.url
  end

  def thumbnail_url
    if is_image?
      self.upload.url(:thumb)
    else
      DEFAULT_THUMBNAIL_URL
    end
  end

  private
    def file_does_not_exist
      Asset.where(upload_file_name: self.upload_file_name).each do |asset|
        next if asset.id = self.id
        errors[:base] << "File named #{self.upload_file_name} already exists"
        return
      end
    end
end

app/controllers/admin/assets_controller.rb
class Admin::AssetsController < ApplicationController
  layout 'admin'

  before_filter :require_user

  DEFAULT_PAGE_SIZE = 20

  def index
    @page = (params[:page] || 1).to_i
    @per_page = (params[:per_page] || DEFAULT_PAGE_SIZE).to_i
    @assets = Asset.by_date_descending.paginate(:page => @page, :per_page => @per_page)
  end

  def show
    @asset = Asset.find(params[:id])
  end

  def new
    @asset = Asset.new
    @user = @current_user
  end

  def edit
    @asset = Asset.find(params[:id])
    if check_access(@asset, 'edit')
      @user = @current_user
    end
  end

  def create
    @asset = Asset.new(asset_param)
    @user = User.find(params[:asset][:user_id])
    @asset.user = @user
    if @asset.save
      redirect_to(admin_asset_path(@asset), :notice => 'Created asset')
    else
      render :action => "new"
    end
  end

  def update
    @asset = Asset.find(params[:id])
    @user = User.find(params[:asset][:user_id])
    if params[:cancel]
      redirect_to(admin_asset_path(@asset))
    elsif check_access(@asset, 'update')
      @asset.attributes = asset_param
      did_change = @asset.changed?
      if @asset.save
        flash[:notice] = 'No changes' unless did_change
        flash[:notice] = 'Updated asset' if did_change
        redirect_to(admin_asset_path(@asset))
      else
        render :action => "edit"
      end
    end
  end

  def destroy
    @asset = Asset.find(params[:id])
    if check_access(@asset, 'delete')
      @asset.destroy
      redirect_to(admin_assets_path)
    end
  end

  private
    def check_access(asset, action)
      return true if asset.user == @current_user
      flash[:error] = "Can only #{action} your own assets"
      redirect_to(admin_asset_path(asset))
      false
    end

    def asset_param(_params = params)
      _params.require(:asset).permit(:user_id, :title, :upload)
    end
end

app/views/admin/assets/edit.html.haml
%h2
  Edit asset #{@asset.id}
%fieldset.admin
  = form_for @asset, :url => admin_asset_path(@asset), :html => { :multipart => true } do |form|
    = render :partial => '/admin/errors', :locals => { :errors => @asset.errors }
    = form.hidden_field :user_id, :value => @user.id
    %div
      = form.label :title
      = form.text_field :title
    .actions
      = form.submit 'Update', :class => 'button', :name => 'update'
      = form.submit 'Cancel', :class => 'button', :name => 'cancel'

app/views/admin/assets/index.html.haml
= link_to('New asset', new_admin_asset_path, :class => 'new')
%h2 Assets
%fieldset.admin
  = will_paginate @assets
  - if @assets.empty?
    No assets yet
  - else
    - unless @assets.empty?
      %table
        %tr
          %th Thumbnail
          %th Title
          %th Url
          %th Content type
          %th Size
          %th Uploaded by
        - @assets.each do |asset|
          %tr{:class => "#{cycle('dark', 'light')}#{" not-author" if asset.user != @current_user}"}
            %td.thumbnail= link_to(image_tag(asset.thumbnail_url), asset.url) if asset.url
            %td= link_to(asset.title, admin_asset_path(asset))
            %td= asset.url.split('?')[0]
            %td= asset.upload_content_type
            %td= number_with_delimiter(asset.upload_file_size)
            %td= asset.user.name
      = will_paginate @assets

app/views/admin/assets/new.html.haml
%h2 New asset
%fieldset.admin
  = form_for @asset, :url => admin_assets_path, :html => { :multipart => true } do |form|
    = render :partial => '/admin/errors', :locals => { :errors => @asset.errors }
    = form.hidden_field :user_id, :value => @user.id
    %div
      = form.label :title
      = form.text_field :title
    %div
      %label Upload
      = form.file_field :upload
    %div
      = form.submit 'Create', :class => 'button'

app/views/admin/assets/show.html.haml
= link_to('New asset', new_admin_asset_path, :class => 'new')
%h2
  Asset #{@asset.id}
%fieldset.admin
  .show
    %span
      %label Title:
      = @asset.title
    %span
      %label Filename:
      = @asset.upload_file_name
    %span
      %label Content type:
      = @asset.upload_content_type
    %span
      %label Size:
      = number_with_delimiter(@asset.upload_file_size)
    %span
      %label URL:
      = link_to(@asset.url.split('?')[0], @asset.url)
    %span
      %label Uploaded by:
      = @asset.user.name
    %span
      %label Created at:
      = format_timestamp(@asset.created_at)
    %span
      %label Updated at:
      = format_timestamp(@asset.updated_at)
    %span
      %label Thumbnail:
    .thumbnail= link_to(image_tag(@asset.thumbnail_url), @asset.url) if @asset.url
    .actions
      = button(admin_assets_path, '« Assets'.html_safe)
      = button(edit_admin_asset_path(@asset), 'Edit')
      = button_with_confirmation(admin_asset_path(@asset), 'Delete', 'Are you sure you want to delete this asset?', 'delete')