config/routes.rb
Rails.application.routes.draw do
  delete '/admin/comments/clear_junk' => 'admin/comments#clear_junk', :as => :clear_junk

  namespace :admin do
    resource :profile, :controller => 'users'
    resource :user_session, :only => :create
    resources :posts do
      post :publish
      post :quietly_publish
      post :revert
      post :takedown
    end
    resources :comments do
      post :junk
      post :notjunk
      collection do
        post :bulk_action
      end
    end
    resources :assets
    resources :tags
    resources :dashboard, :only => :index
  end

  get '/register' => 'admin/users#new'
  get '/login' => 'admin/user_sessions#new'
  get '/logout' => 'admin/user_sessions#destroy'

  get '/admin' => redirect('/admin/dashboard')

  get '/posts.:format' => 'home#posts', :format => 'atom'
  get '/comments.:format', :controller => 'home', :action => 'comments', :format => 'atom'

  get '/:tag/posts.:format', :controller => 'home', :action => 'posts', :format => 'atom'
  get '/:post/comments.:format', :controller => 'home', :action => 'comments', :format => 'atom'

  get '/tag/:label' => 'home#tag'
  get '/tag/:label.:format' => 'home#tag'

  get '/:permalink' => 'home#post'
  get '/:permalink/preview' => 'home#preview'
  get '/:permalink.:format' => 'home#post'

  post '/:permalink' => 'home#post'

  get ':controller(/:id(/:action(/:id)))'
  get ':controller(/:id(/:action(/:id(.:format))))'

  root :to => "home#index"
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :posts_tags
  has_many :posts, :through => :posts_tags

  before_validation :generate_permalink

  validate :check_permalink
  validates_uniqueness_of :permalink, :label
  validates_presence_of :label

  scope :by_label, -> { order(label: :asc) }
  scope :with_posts, -> { joins('JOIN posts_tags pt ON pt.tag_id = tags.id') }
  scope :with_published_posts, -> { joins('JOIN posts_tags pt ON pt.tag_id = tags.id', 'JOIN posts p ON p.id = pt.post_id').where('p.version IS NOT NULL') }

  def permalink_url
    "/tag/#{self.permalink}"
  end

  private
    def generate_permalink
      return unless self.permalink.blank?
      return if self.label.nil?
      self.permalink = "#{label.downcase.gsub(/[^A-Za-z0-9 ]/, '').gsub(' ', '-')}"
    end

    def check_permalink
      unless self.permalink.match(/^([a-zA-Z0-9]|-)*$/)
        errors.add(:permalink, "can only contain alphanumerics and dashes")
      end
    end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  layout 'admin'

  before_filter :require_user

  def index
    @tags = Tag.by_label
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def new
    @tag = Tag.new
  end

  def edit
    @tag = Tag.find(params[:id])
    check_access(@tag, 'edit')
  end

  def create
    @tag = Tag.new(tag_param)
    if @tag.save
      redirect_to(admin_tag_path(@tag), :notice => 'Created tag')
    else
      render :action => "new"
    end
  end

  def update
    @tag = Tag.find(params[:id])
    if params[:cancel]
      redirect_to(admin_tag_path(@tag))
    elsif check_access(@tag, 'update')
      @tag.attributes = tag_param
      did_change = @tag.changed?
      if @tag.save
        flash[:notice] = 'No changes' unless did_change
        flash[:notice] = 'Updated tag' if did_change
        redirect_to(admin_tag_path(@tag))
      else
        render :action => "edit"
      end
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    if check_access(@tag, 'delete')
      @tag.destroy
      redirect_to(admin_tags_path)
    end
  end

  private
    def check_access(tag, action)
      return true if tag.posts.published.all?{ |post| post.user_id == @current_user.id }
      flash[:error] = "Cannot #{action} a tag that is used by published posts not belonging to you"
      redirect_to(admin_tag_path(tag))
      false
    end

    def tag_param
      params.require(:tag).permit(:label, :permalink)
    end
end

app/views/admin/tags/_form.html.haml
%div
  = form.label :label
  = form.text_field :label
%div
  = form.label :permalink, 'Permalink [leave blank to auto-generate]'
  = form.text_field :permalink

app/views/admin/tags/edit.html.haml
%h2
  Editing tag #{@tag.id}
%fieldset.admin
  = form_for @tag, :url => admin_tag_path(@tag) do |form|
    = render :partial => '/admin/errors', :locals => { :errors => @tag.errors }
    = render :partial => 'form', :object => form
    .actions
      = form.submit 'Update', :class => 'button', :name => 'update'
      = form.submit 'Cancel', :class => 'button', :name => 'cancel'

app/views/admin/tags/index.html.haml
= link_to('New tag', new_admin_tag_path, :class => 'new')
%h2 Tags
%fieldset.admin
  - if @tags.empty?
    No tags yet
  - else
    - unless @tags.empty?
      %table
        %tr
          %th Tag
          %th Current posts
          %th Outdated posts
          %th Unpublished posts
        - @tags.each do |tag|
          %tr{:class => cycle('dark', 'light')}
            %td
              %span.permalink
                = link_to(image_tag('/images/permalink.png', :title => 'permalink'), tag.permalink_url) if tag.permalink_url
              = link_to(tag.label, admin_tag_path(tag))
            %td= tag.posts.current.empty? ? '0' : link_to("#{tag.posts.current.count}", admin_posts_path(:tag_id => tag.id, :publish_status => 'current'))
            %td= tag.posts.outdated.empty? ? '0' : link_to("#{tag.posts.outdated.count}", admin_posts_path(:tag_id => tag.id, :publish_status => 'outdated'))
            %td= tag.posts.unpublished.empty? ? '0' : link_to("#{tag.posts.unpublished.count}", admin_posts_path(:tag_id => tag.id, :publish_status => 'unpublished'))

app/views/admin/tags/new.html.haml
%h2 New tag
%fieldset.admin
  = form_for @tag, :url => admin_tags_path do |form|
    = render :partial => '/admin/errors', :locals => { :errors => @tag.errors }
    = render :partial => 'form', :object => form
    .actions
      = form.submit 'Create', :class => 'button'

app/views/admin/tags/show.html.haml
= link_to('New tag', new_admin_tag_path, :class => 'new')
%h2
  Tag #{@tag.id}
%fieldset.admin
  .show
    %span
      %label Label:
      = @tag.label
    %span
      %label Posts:
      = @tag.posts.count
    %span
      %label Permalink:
      = link_to "tag/#{@tag.permalink}", @tag.permalink_url
    .actions
      = button(admin_tags_path, '« Tags'.html_safe)
      = button(edit_admin_tag_path(@tag), 'Edit')
      = button_with_confirmation(admin_tag_path(@tag), 'Delete', 'Are you sure you want to delete this tag?', 'delete')