config/routes.rb
Rails.application.routes.draw do
  delete '/admin/comments/clear_junk' => 'admin/comments#clear_junk', :as => :clear_junk

  namespace :admin do
    resource :profile, :controller => 'users'
    resource :user_session, :only => :create
    resources :posts do
      post :publish
      post :quietly_publish
      post :revert
      post :takedown
    end
    resources :comments do
      post :junk
      post :notjunk
      collection do
        post :bulk_action
      end
    end
    resources :assets
    resources :tags
    resources :dashboard, :only => :index
  end

  get '/register' => 'admin/users#new'
  get '/login' => 'admin/user_sessions#new'
  get '/logout' => 'admin/user_sessions#destroy'

  get '/admin' => redirect('/admin/dashboard')

  get '/posts.:format' => 'home#posts', :format => 'atom'
  get '/comments.:format', :controller => 'home', :action => 'comments', :format => 'atom'

  get '/:tag/posts.:format', :controller => 'home', :action => 'posts', :format => 'atom'
  get '/:post/comments.:format', :controller => 'home', :action => 'comments', :format => 'atom'

  get '/tag/:label' => 'home#tag'
  get '/tag/:label.:format' => 'home#tag'

  get '/:permalink' => 'home#post'
  get '/:permalink/preview' => 'home#preview'
  get '/:permalink.:format' => 'home#post'

  post '/:permalink' => 'home#post'

  get ':controller(/:id(/:action(/:id)))'
  get ':controller(/:id(/:action(/:id(.:format))))'

  root :to => "home#index"
end

app/views/layouts/admin.html.haml
!!!
%html{:lang => "en", "xml:lang" => "en", :xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "text/html;charset=UTF-8", "http-equiv" => "content-type"}/
    %title
      = controller.action_name
      = controller.controller_name
      \- blog admin
    = stylesheet_link_tag 'admin'
    = stylesheet_link_tag 'content'
    = stylesheet_link_tag 'prettify'
    = stylesheet_link_tag '/markitup/skins/simple/style.css'
    = stylesheet_link_tag '/markitup/sets/badass/style.css'
    = javascript_include_tag APP_CONFIG.jquery_lib
    = javascript_include_tag '/javascripts/badass.js'
    = javascript_include_tag '/javascripts/application.js'
    = javascript_include_tag src='/markitup/jquery.markitup.js'
    = javascript_include_tag src='/markitup/sets/badass/set.js'
    = csrf_meta_tag
  %body{:onload => "prettyPrint()"}
    %h1 Blog Admin
    #title-bar
      - if current_user
        %span#login-info
          = current_user.login
          logged in
      %ul
        - if !current_user
          - if User.can_register?
            %li= link_to 'Register', register_path
          = link_to 'Log In', login_path
        - else
          %li= link_to 'Dashboard', admin_dashboard_index_path
          %li= link_to 'Tags', admin_tags_path
          %li= link_to 'Posts', admin_posts_path
          %li= link_to 'Comments', admin_comments_path
          %li= link_to 'Assets', admin_assets_path
          %li= link_to 'Profile', admin_profile_path
          %li= link_to 'Logout', logout_path, :method => :delete, :confirm => "Are you sure you want to logout?"
    - if flash[:error]
      %p.flash.error= flash[:error]
    - elsif flash[:notice]
      %p.flash.notice= flash[:notice]
    = yield
  = javascript_include_tag '/javascripts/prettify.js'

app/views/layouts/home.html.haml
!!!
%html{:lang => "en", "xml:lang" => "en", :xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "text/html;charset=UTF-8", "http-equiv" => "content-type"}/
    %meta{:content => keywords, :name => "keywords"}/
    %meta{:content => APP_CONFIG.blog_description, :name => "description"}/
    %title= APP_CONFIG.blog_title
    %link{:href => posts_feed_url, :rel => "alternate", :title => posts_feed_title, :type => "application/atom+xml"}/
    - if @tag
      %link{:href => posts_feed_url(@tag), :rel => "alternate", :title => posts_feed_title(@tag), :type => "application/atom+xml"}/
    %link{:href => comments_feed_url, :rel => "alternate", :title => comments_feed_title, :type => "application/atom+xml"}/
    = stylesheet_link_tag 'site'
    = stylesheet_link_tag 'content'
    = stylesheet_link_tag 'prettify'
    = javascript_include_tag APP_CONFIG.jquery_lib
    = javascript_include_tag '/javascripts/badass.js'
    = javascript_include_tag '/javascripts/application.js'
    = csrf_meta_tag
    = render :partial => 'analytics'
  %body{:onload => "prettyPrint()"}
    .main-wrapper
      .main
        %h1= link_to APP_CONFIG.blog_title, '/'
        = yield
      .sidebar
        = render :partial => 'about'
        = render :partial => 'tags'
        = render :partial => 'contents'
        = render :partial => 'tweets'
        = render :partial => 'powered'
      = javascript_include_tag '/javascripts/prettify.js'

app/views/layouts/post.html.haml
!!!
%html{:lang => "en", "xml:lang" => "en", :xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "text/html;charset=UTF-8", "http-equiv" => "content-type"}/
    %meta{:content => @post.user.name, :name => "author"}/
    %meta{:content => keywords(@post), :name => "keywords"}/
    %meta{:content => @post.title || @post.title_draft, :name => "description"}/
    %title
      = @post.title || @post.title_draft
      \- #{APP_CONFIG.blog_title}
    - if @post.published?
      %link{:href => posts_feed_url, :rel => "alternate", :title => posts_feed_title, :type => "application/atom+xml"}/
      %link{:href => comments_feed_url, :rel => "alternate", :title => comments_feed_title, :type => "application/atom+xml"}/
      %link{:href => comments_feed_url(@post), :rel => "alternate", :title => comments_feed_title(@post), :type => "application/atom+xml"}/
    = stylesheet_link_tag 'site'
    = stylesheet_link_tag 'content'
    = stylesheet_link_tag 'prettify'
    = javascript_include_tag APP_CONFIG.jquery_lib
    = javascript_include_tag '/javascripts/badass.js'
    = javascript_include_tag '/javascripts/application.js'
    = csrf_meta_tag
    = render :partial => 'analytics'
  %body{:onload => "prettyPrint()"}
    .main-wrapper
      .main
        %h1= link_to APP_CONFIG.blog_title, '/'
        = yield
      .sidebar
        = render :partial => 'tags'
        = render :partial => 'contents'
        = render :partial => 'tweets'
        = render :partial => 'powered'
      = javascript_include_tag '/javascripts/prettify.js'